name: 'aws_ecommerce'
version: '1.0.0'

require-dbt-version: [">=1.9.0"]

profile: 'aws_ecommerce'

quoting:
  database: false
  schema: true
  identifier: true

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  aws_ecommerce:
    +schema: raw

models:
  aws_ecommerce:
    staging:
      +schema: staging
      +materialized: view
      +access: protected
    intermediate:
      +schema: intermediate
      +materialized: view
      +access: protected
    marts:
      +schema: marts
      +materialized: table
      +access: public
      +persist_docs:
        relation: true
        columns: true
